In [2]:
#import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
#this dataset is choose for this project because it includes 9 standardized questions assessing depression symptoms
#the dataset has the answers represented numbers as shown on the report of this open data set https://data.mendeley.com/datasets/kkzjk253cy/6 
#also useful for my project as the data set is from young adults aged 17-26 years
#Responses are scored on a 4-point scale from 0 (Not at all) to 3 (Nearly every day) with total scores ranging from 0 to 27

#Minimal (0-4): 206 participants (30.2%)
#Mild (5-9): 155 participants (22.7%)
#Moderate (10-14): 128 participants (18.8%)
#Moderately Severe (15-19): 125 participants (18.3%)
#Severe (20-27): 68 participants (10.0%)
#for my prject i will group minimal and mild and moderate and moderately severtely and servere so there are 3 groups

In [3]:
data=pd.read_csv("C:/Users/Shaiz/Downloads/PHQ-9_Dataset_5th Edition.csv")
list(data)#will remove the unrelavent columns so age gender and  'PHQ_Severity','Sleep Quality' 'Study Pressure','Financial Pressure']

['Age',
 'Gender',
 'Little interest or pleasure in doing things ',
 '  Feeling down, depressed, or hopeless  ',
 '  Trouble falling or staying asleep, or sleeping too much  ',
 '  Feeling tired or having little energy  ',
 '  Poor appetite or overeating  ',
 'Feeling bad about yourself—or that you are a failure or have let yourself or your family down  ',
 'Trouble concentrating on things, such as reading the newspaper or watching television  ',
 'Moving or speaking so slowly that other people could have noticed? Or the opposite—being so fidgety or restless that you have been moving around a lot more than usual  ',
 'Thoughts that you would be better off dead or of hurting yourself in some way  ',
 'PHQ_Total',
 'PHQ_Severity',
 'Sleep Quality',
 'Study Pressure',
 'Financial Pressure']

In [4]:
del data['Age']
del data['Gender']
del data['Sleep Quality']
del data ['Study Pressure']
del data['Financial Pressure']
del data['PHQ_Severity']#removing these because there are not useful for the app

In [5]:
list(data)

['Little interest or pleasure in doing things ',
 '  Feeling down, depressed, or hopeless  ',
 '  Trouble falling or staying asleep, or sleeping too much  ',
 '  Feeling tired or having little energy  ',
 '  Poor appetite or overeating  ',
 'Feeling bad about yourself—or that you are a failure or have let yourself or your family down  ',
 'Trouble concentrating on things, such as reading the newspaper or watching television  ',
 'Moving or speaking so slowly that other people could have noticed? Or the opposite—being so fidgety or restless that you have been moving around a lot more than usual  ',
 'Thoughts that you would be better off dead or of hurting yourself in some way  ',
 'PHQ_Total']

In [6]:
data

,Little interest or pleasure in doing things,"Feeling down, depressed, or hopeless","Trouble falling or staying asleep, or sleeping too much",Feeling tired or having little energy,Poor appetite or overeating,Feeling bad about yourself—or that you are a failure or have let yourself or your family down,"Trouble concentrating on things, such as reading the newspaper or watching television",Moving or speaking so slowly that other people could have noticed? Or the opposite—being so fidgety or restless that you have been moving around a lot more than usual,Thoughts that you would be better off dead or of hurting yourself in some way,PHQ_Total
0,More than half the days,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,More than half the days,Not at all,4
1,Not at all,Not at all,Nearly every day,Nearly every day,Nearly every day,Not at all,More than half the days,More than half the days,More than half the days,15
2,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,1
3,Nearly every day,Nearly every day,Not at all,Nearly every day,More than half the days,Not at all,Not at all,Not at all,Not at all,11
4,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,More than half the days,Not at all,2
...,...,...,...,...,...,...,...,...,...,...
677,More than half the days,Nearly every day,Several days,More than half the days,Nearly every day,Nearly every day,Nearly every day,Not at all,Several days,18
678,Nearly every day,More than half the days,Several days,More than half the days,More than half the days,Nearly every day,Nearly every day,Nearly every day,Nearly every day,22
679,Not at all,Not at all,More than half the days,More than half the days,Not at all,Several days,Several days,Several days,More than half the days,9
680,Not at all,Several days,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,2
681,Nearly every day,Several days,Nearly every day,Nearly every day,Several days,More than half the days,Not at all,Nearly every day,More than half the days,18

In [7]:
#check for missing data
print(data.isnull().sum())

Little interest or pleasure in doing things                                                                                                                                 0
  Feeling down, depressed, or hopeless                                                                                                                                      0
  Trouble falling or staying asleep, or sleeping too much                                                                                                                   0
  Feeling tired or having little energy                                                                                                                                     0
  Poor appetite or overeating                                                                                                                                               0
Feeling bad about yourself—or that you are a failure or have let yourself or your family down                                                                               0
Trouble concentrating on things, such as reading the newspaper or watching television                                                                                       0
Moving or speaking so slowly that other people could have noticed? Or the opposite—being so fidgety or restless that you have been moving around a lot more than usual      0
Thoughts that you would be better off dead or of hurting yourself in some way                                                                                               0
PHQ_Total                                                                                                                                                                   0
dtype: int64

In [8]:
mapping = {
    "Not at all": 0,
    "Several days": 1,
    "More than half the days": 2,
    "Nearly every day": 3
}

question_columns = data.columns.drop("PHQ_Total")
#based on the data using answers that are also based on number as it showns in the report of where this database was found i change the answrs to the numbers 
data[question_columns] = data[question_columns].replace(mapping)

C:\Users\Shaiz\AppData\Local\Temp\ipykernel_23040\1721650093.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[question_columns] = data[question_columns].replace(mapping)

In [9]:
data

,Little interest or pleasure in doing things,"Feeling down, depressed, or hopeless","Trouble falling or staying asleep, or sleeping too much",Feeling tired or having little energy,Poor appetite or overeating,Feeling bad about yourself—or that you are a failure or have let yourself or your family down,"Trouble concentrating on things, such as reading the newspaper or watching television",Moving or speaking so slowly that other people could have noticed? Or the opposite—being so fidgety or restless that you have been moving around a lot more than usual,Thoughts that you would be better off dead or of hurting yourself in some way,PHQ_Total
0,2,0,0,0,0,0,0,2,0,4
1,0,0,3,3,3,0,2,2,2,15
2,0,0,0,0,0,0,1,0,0,1
3,3,3,0,3,2,0,0,0,0,11
4,0,0,0,0,0,0,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...
677,2,3,1,2,3,3,3,0,1,18
678,3,2,1,2,2,3,3,3,3,22
679,0,0,2,2,0,1,1,1,2,9
680,0,1,0,0,0,1,0,0,0,2
681,3,1,3,3,1,2,0,3,2,18

In [27]:
#so clustering groups will be 
#mild (0-9):
#Moderate (10-19): 
#Severe (20-27):

X = data[question_columns]

kmeans = KMeans(n_clusters=3, random_state=42)
data["Cluster"] = kmeans.fit_predict(X)
cluster_summary = data.groupby("Cluster")["PHQ_Total"].mean()

print(cluster_summary)

Cluster
0     3.542056
1    12.202765
2    20.618056
Name: PHQ_Total, dtype: float64

C:\Users\Shaiz\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(

In [28]:
cluster_means = data.groupby("Cluster")["PHQ_Total"].mean().sort_values()


severity_map = {
    cluster_means.index[0]: "Mild",
    cluster_means.index[1]: "Moderate",
    cluster_means.index[2]: "Severe"
}

data["Severity_Group"] = data["Cluster"].map(severity_map)

print(data[["PHQ_Total", "Cluster", "Severity_Group"]].head())

   PHQ_Total  Cluster Severity_Group
0          4        0           Mild
1         15        1       Moderate
2          1        0           Mild
3         11        1       Moderate
4          2        0           Mild